// <auto-generated />
using System;
using MakFood.Kitchen.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakFood.Kitchen.Infrastructure.Persistence.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.CartAggrigate.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ProductThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.CategoryAggrigate.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.CategoryAggrigate.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiscountPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MaximumBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountPolicyId")
                        .IsUnique();

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.DiscountPolicyAggrigate.DiscountPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountPolicyType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiscountPolicy");

                    b.HasDiscriminator<string>("DiscountPolicyType").HasValue("DiscountPolicy");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.FoodRequestAggrigate.FoodRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("FoodRequests");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.Constituent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Constituent");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DiscountCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Payable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountCodeId")
                        .IsUnique()
                        .HasFilter("[DiscountCodeId] IS NOT NULL");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.OrderState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderState");

                    b.HasDiscriminator<string>("OrderState").HasValue("OrderState");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.PaymentBase.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OwnerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OwnerPaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OwnerPaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<decimal>("ReminingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasDiscriminator<string>("PaymentType").HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.PaymentState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentState");

                    b.HasDiscriminator().HasValue("PaymentState");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.ProductAggrigate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AvailableQuantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SubCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.DiscountPolicyAggrigate.AllPermittedPolicy", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.DiscountPolicyAggrigate.DiscountPolicy");

                    b.HasDiscriminator().HasValue("AllPermittedPolicy");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.DiscountPolicyAggrigate.SpecifiedPermisionPolicy", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.DiscountPolicyAggrigate.DiscountPolicy");

                    b.HasDiscriminator().HasValue("SpecifiedPermisionPolicy");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.CancelledOrderState", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.OrderState");

                    b.HasDiscriminator().HasValue("CancelledOrderState");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.CreatedOrderState", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.OrderState");

                    b.HasDiscriminator().HasValue("CreatedOrderState");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.MiseOnPlaceOrderState", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.OrderState");

                    b.HasDiscriminator().HasValue("MiseOnPlaceOrderState");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.SharedPayment", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.PaymentBase.Payment");

                    b.Property<decimal>("PartnerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PartnerApproved")
                        .HasColumnType("bit");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PartnerPaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PartnerPaymentMethod")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SharedPayment");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.SinglePayment", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.PaymentBase.Payment");

                    b.HasDiscriminator().HasValue("SinglePayment");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.CancelledPaymentState", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.PaymentState");

                    b.HasDiscriminator().HasValue("CancelledPaymentState");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.CreatedPaymentState", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.PaymentState");

                    b.HasDiscriminator().HasValue("CreatedPaymentState");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.PaidPaymentState", b =>
                {
                    b.HasBaseType("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.PaymentState");

                    b.HasDiscriminator().HasValue("PaidPaymentState");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.CartAggrigate.CartItem", b =>
                {
                    b.HasOne("Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.CategoryAggrigate.Subcategory", b =>
                {
                    b.HasOne("MakFood.Kitchen.Domain.Entities.CategoryAggrigate.Category", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.Discount", b =>
                {
                    b.HasOne("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.DiscountPolicyAggrigate.DiscountPolicy", "DiscountPolicy")
                        .WithOne()
                        .HasForeignKey("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.Discount", "DiscountPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountPolicy");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.Constituent", b =>
                {
                    b.HasOne("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.Order", null)
                        .WithMany("Consistencies")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.Order", b =>
                {
                    b.HasOne("MakFood.Kitchen.Domain.Entities.DiscountAggrigate.Discount", "DiscountCode")
                        .WithOne()
                        .HasForeignKey("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.Order", "DiscountCodeId");

                    b.HasOne("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.PaymentBase.Payment", "Payment")
                        .WithOne()
                        .HasForeignKey("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.Order", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountCode");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.OrederState.OrderState", b =>
                {
                    b.HasOne("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.Order", null)
                        .WithMany("StateHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.State.PaymentState", b =>
                {
                    b.HasOne("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.PaymentBase.Payment", null)
                        .WithMany("PaymentLog")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.CategoryAggrigate.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.Order", b =>
                {
                    b.Navigation("Consistencies");

                    b.Navigation("StateHistory");
                });

            modelBuilder.Entity("MakFood.Kitchen.Domain.Entities.OrderAggrigate.OrderAggrigate.PaymentAggrigate.PaymentBase.Payment", b =>
                {
                    b.Navigation("PaymentLog");
                });
#pragma warning restore 612, 618
        }
    }
}
